version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  test:
    docker:
    - image: cimg/go:1.22.0
    working_directory: ~/ksplit
    steps:
    - checkout
    - run:
        name: go test
        command: |
          make citest
    - codecov/upload:
        file: .state/coverage.out
    - run:
        name: build
        command: |
          make build

workflows:
  version: 2

  unstable:
    jobs:
    - test
